name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nix flake
        run: |
          nix develop --command echo "✅ Nix flake evaluation successful"

      - name: Check available tools
        run: |
          nix develop --command swift --version
          nix develop --command protoc --version
          nix develop --command protoc-gen-swift --version

      - name: Build grpc-swift-protobuf
        run: |
          nix develop --command build-grpc-swift-protobuf

      - name: Check plugin status
        run: |
          nix develop --command check-grpc-plugin

      - name: Test code generation
        run: |
          mkdir -p generated
          nix run .#codegen -- -o generated examples/proto/greet.proto

          # Verify generated files exist
          ls -la generated/
          test -f generated/greet.pb.swift
          test -f generated/greet.grpc.swift

          echo "✅ Code generation successful"

    #   - name: Upload generated artifacts
    #     uses: actions/upload-artifact@v4
    #     if: always()
    #     with:
    #       name: generated-code-${{ matrix.os }}
    #       path: generated/
    #       retention-days: 7

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check README format
        run: |
          # Check if README.md exists and has basic content
          test -f README.md
          grep -q "grpc-swift-2-flake" README.md
          echo "✅ README format check passed"

      - name: Check flake.nix format
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Validate flake
        run: |
          nix flake check --no-build
          echo "✅ Flake validation passed"
